export const container: string;
export const repo_title: string;
export const repoTitle: string;
export const repo_data: string;
export const repoData: string;
export const lang_color: string;
export const langColor: string;
export const forked_from: string;
export const forkedFrom: string;
